version: '3'

services:
    verdaccio:
        image: verdaccio/verdaccio
        container_name: verdaccio
        ports:
            - 4873:4873
        volumes:
            - ./conf:/verdaccio/conf
        networks:
            - verdaccio

networks:
    verdaccio:
