instrumentation:
    excludes:
        - "out/**"
        - "scripts/**"
        - "integration-test/**"
check:
    global:
        statements: 95
        lines: 95
        branches: 95
        functions: 95
