instrumentation:
    excludes:
        - ".vscode/*"
        - "config/*"
        - "dist/*"
        - "docker/*"
check:
    global:
        statements: 54
        branches: 30
        functions: 42
        lines: 53
