instrumentation:
    excludes:
        - ".vscode/*"
        - "config/*"
        - "dist/*"
        - "docker/*"
check:
    global:
        statements: 82
        branches: 76
        functions: 72
        lines: 81
