instrumentation:
    excludes:
        - ".vscode/*"
        - "config/*"
        - "dist/*"
        - "docker/*"
check:
    global:
        statements: 99.4
        branches: 96.5
        functions: 98.8
        lines: 99.4
