instrumentation:
    excludes:
        - ".vscode/*"
        - "config/*"
        - "dist/*"
        - "docker/*"
check:
    global:
        statements: 99
        branches: 95
        functions: 98
        lines: 99
