instrumentation:
    excludes:
        - ".vscode/*"
        - "config/*"
        - "dist/*"
        - "docker/*"
check:
    global:
        statements: 99
        branches: 96.3
        functions: 98.9
        lines: 99.3
