instrumentation:
    excludes:
        - ".vscode/*"
        - "config/*"
        - "dist/*"
        - "docker/*"
check:
    global:
        statements: 63
        branches: 52
        functions: 49
        lines: 63
