instrumentation:
    excludes:
        - ".vscode/*"
        - "config/*"
        - "dist/*"
        - "docker/*"
check:
    global:
        statements: 99.51
        branches: 97.12
        functions: 98.93
        lines: 99.55
