instrumentation:
    excludes:
        - ".vscode/*"
        - "config/*"
        - "dist/*"
        - "docker/*"
check:
    global:
        statements: 99.76
        branches: 98.65
        functions: 98.83
        lines: 99.8
