version: "2"
services:
  membersrvc:
    image: hyperledger/fabric-membersrvc:x86_64-0.6.1-preview
    ports:
      - '7054:7054'
    environment:
      - MEMBERSRVC_CA_ACA_ENABLED=true
    command: membersrvc
  vp0:
    image: hyperledger/fabric-peer:x86_64-0.6.1-preview
    ports:
      - '7050:7050'
      - '7051:7051'
      - '7052:7052'
      - '7053:7053'
    environment:
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=vp0
      - CORE_PEER_PKI_ECA_PADDR=membersrvc:7054
      - CORE_PEER_PKI_TCA_PADDR=membersrvc:7054
      - CORE_PEER_PKI_TLSCA_PADDR=membersrvc:7054
      - CORE_SECURITY_ENABLED=true
      - CORE_SECURITY_ENROLLID=test_vp0
      - CORE_SECURITY_ENROLLSECRET=MwYpmSRjupbT
    links:
      - membersrvc
    command: sh -c 'sleep 5; peer node start'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  composer:
    image: hyperledger/composer-playground
    ports:
      - '8080:8080'
    links:
      - vp0
      - membersrvc
    environment:
      COMPOSER_CONFIG: >
        {
          "connectionProfiles": {
            "hlfabric": {
              "type": "hlf",
              "keyValStore": "/home/composer/.composer-credentials",
              "membershipServicesURL": "grpc://membersrvc:7054",
              "peerURL": "grpc://vp0:7051",
              "eventHubURL": "grpc://vp0:7053",
              "deployWaitTime": 300,
              "invokeWaitTime": 30
            }
          },
          "credentials": {
            "hlfabric": {
              "admin": "Xurw3yU9zI0l"
            }
          }
        }
